server:
  port: 8183
  servlet:
    context-path: /handbook
  tomcat:
    accesslog:
      request-attributes-enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 5432
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    dispatch-trace-request: true